from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Pheonix(object):
    def setupUi(self, Pheonix):
        Pheonix.setObjectName("Pheonix")
        Pheonix.resize(1469, 784)
        self.label_3 = QtWidgets.QLabel(Pheonix)
        self.label_3.setGeometry(QtCore.QRect(760, 0, 711, 541))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("GIF/39f6a005763b37e2237b320df0e68e31.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Pheonix)
        self.label_5.setGeometry(QtCore.QRect(460, 530, 441, 251))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("GIF/tumblr_nrqm32yH3W1r6xm5co1_1280.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(Pheonix)
        self.label_2.setGeometry(QtCore.QRect(870, 510, 321, 271))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("GIF/9e759fd37ccd98da121b670249f34afa.gif"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(Pheonix)
        self.label_6.setGeometry(QtCore.QRect(1180, 520, 291, 261))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("GIF/tumblr_o7vrxl8Uk11runoqyo2_540.gif"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(Pheonix)
        self.label_4.setGeometry(QtCore.QRect(-20, 540, 521, 241))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("GIF/Untitled.jpg"))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(Pheonix)
        self.label.setGeometry(QtCore.QRect(-100, 0, 861, 541))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("GIF/dc8436d03012b7204637ed7207a05808.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(Pheonix)
        self.label_7.setGeometry(QtCore.QRect(30, 480, 1081, 61))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("GIF/8ee7d93c9b015c00938a4091c3ef443e951d1518_hq.gif"))
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(Pheonix)
        self.pushButton.setGeometry(QtCore.QRect(600, 340, 381, 81))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Pheonix)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 440, 381, 81))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Pheonix)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 570, 211, 81))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Pheonix)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 570, 211, 81))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Pheonix)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 680, 211, 81))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Pheonix)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 680, 211, 81))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Pheonix)
        self.pushButton_7.setGeometry(QtCore.QRect(610, 40, 321, 171))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setMouseTracking(False)
        self.pushButton_7.setStyleSheet("background:transperent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:60px;")
        self.pushButton_7.setObjectName("textBrowser")

        self.retranslateUi(Pheonix)
        QtCore.QMetaObject.connectSlotsByName(Pheonix)

    def retranslateUi(self, Pheonix):
        _translate = QtCore.QCoreApplication.translate
        Pheonix.setWindowTitle(_translate("Pheonix", "Dialog"))
        self.pushButton.setText(_translate("Pheonix", "Press the Button to Start"))
        self.pushButton_2.setText(_translate("Pheonix", "Press this Button to Stop"))
        self.pushButton_3.setText(_translate("Pheonix", "Camera"))
        self.pushButton_4.setText(_translate("Pheonix", "Google"))
        self.pushButton_5.setText(_translate("Pheonix", "Youtube"))
        self.pushButton_6.setText(_translate("Pheonix", "Facebook"))
        self.pushButton_7.setText(_translate("Pheonix", "Pheonix"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Pheonix = QtWidgets.QDialog()
    ui = Ui_Pheonix()
    ui.setupUi(Pheonix)
    Pheonix.show()
    sys.exit(app.exec_())